// This file was generated by [rspc](https://github.com/oscartbeaumont/rspc). Do not edit this file manually.

export type Procedures = {
    queries: 
        { key: "beverage", input: never, result: JoinBeverage[] } | 
        { key: "kind", input: never, result: Kind[] } | 
        { key: "producer", input: never, result: Producer[] },
    mutations: 
        { key: "beverage", input: InsertBeverage, result: null } | 
        { key: "kind", input: NameRequest, result: null } | 
        { key: "producer", input: NameRequest, result: null },
    subscriptions: never
};

export type Kind = { kind_id: number; name: string }

export type InsertBeverage = { name: string; producer_id: number; kind_id: number; rating: number; description: string }

export type Producer = { producer_id: number; name: string }

export type NameRequest = { name: string }

export type JoinBeverage = { name: string; producer: string; kind: string; rating: number; description: string }
