// This file was generated by [rspc](https://github.com/oscartbeaumont/rspc). Do not edit this file manually.

export type Procedures = {
    queries: 
        { key: "beverage", input: never, result: JoinBeverage[] } | 
        { key: "kind", input: never, result: Kind[] } | 
        { key: "producer", input: never, result: Producer[] },
    mutations: 
        { key: "beverage", input: UpdateBeverageRequest, result: null } | 
        { key: "deleteBeverage", input: number, result: null } | 
        { key: "kind", input: NameRequest, result: null } | 
        { key: "producer", input: NameRequest, result: null },
    subscriptions: never
};

export type UpdateBeverageRequest = { beverage_id: number | null; beverage: InsertBeverage }

export type Kind = { kind_id: number; name: string }

export type JoinBeverage = { beverage_id: number; name: string; producer_id: number; producer: string; kind_id: number; kind: string; rating: number; description: string; image: number[] | null }

export type NameRequest = { name: string }

export type InsertBeverage = { name: string; producer_id: number; kind_id: number; rating: number; description: string; image: number[] | null }

export type Producer = { producer_id: number; name: string }
